name: zoo_market
description: ZooMarket mobile application

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state manager
  flutter_bloc: ^7.2.0

  # di
  get_it: ^7.2.0

  #ui
  flutter_svg: ^1.1.6
  cupertino_icons: ^1.0.2
  flutter_masked_text2: ^0.9.1
  pinput: ^1.2.0

  #store
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^7.0.1

  #firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5

  #network
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/fonts/
    - assets/fonts/ceraPro/

  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/ceraPro/CeraPro-Black.ttf
          weight: 900
        - asset: assets/fonts/ceraPro/CeraPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/ceraPro/CeraPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ceraPro/CeraPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ceraPro/CeraPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ceraPro/CeraPro-Thin.ttf
          weight: 200
        - asset: assets/fonts/ceraPro/CeraPro-Thin.ttf
          weight: 100